### ISSUE TITLE
Will you please provide the steps for get the google credentials if possible with screenshots

### ISSUE THREAD

**Issue by hgsongra** [RichIsOnRails/GoogleAuthExampleApp#1]
Hello,

I have download your repo and tried to run it.
but every time I get the following error

`400. That’s an error.

Error: redirect_uri_mismatch

Application: PLEASEGOOLEIT

You can email the developer of this application at: hgsongra@gmail.com

The redirect URI in the request, http://localhost:3001/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/952945813046-mmk1jq8t5twerewrorrd9f31vj089313.apps.googleusercontent.com?project=952945567846 to update the authorized redirect URIs.

Learn more
Request Details

```
access_type=offline
scope=email profile
response_type=code
redirect_uri=http://localhost:3001/auth/google_oauth2/callback
state=dcdc84176235300c878fa8cbcfed935486f37d365706f213
client_id=952945813046-mmk1jsf87f878oorrs9fd8vj089313.apps.googleusercontent.com
```

That’s all we know.`
**Note:** I made changes in client_id and project_id  for security purpose
What is the purpose of cert file, will you please explain?
please provide the solution to resolve this issue.

Thanks,
Hitesh

**Comment by RichIsOnRails** [comment]
You have to make sure you get the callback url correct.  Take a look at my updated article.

**Comment by hitesh-co2** [comment]
Thanks, It resolved my issue.

Updated Article looks good with step by step explanation.

**Comment by hgsongra** [comment]
Thanks, It resolved my issue.

Updated Article looks good with step by step explanation.
